# Generated by Django 4.0.5 on 2022-06-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('setup_time', models.IntegerField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstations', to='enterprise.factory')),
            ],
        ),
        migrations.CreateModel(
            name='SKURouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='sku.sku')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='routing.skurouting')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.sku')),
                ('workstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.workstation')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('routing', 'order')},
            },
        ),
    ]
