# Generated by Django 4.0.5 on 2022-06-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKUCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500)),
                ('is_discrete', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=1000)),
                ('uom', models.CharField(choices=[('piece', 'Piece'), ('gr', 'Gram')], default='piece', max_length=50)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sku.skucategory')),
            ],
        ),
    ]
