# Generated by Django 4.0.5 on 2022-06-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='enterprise.factory')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reserved_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouse')),
            ],
        ),
    ]
